eshop/urls.py
from multiprocessing.resource_tracker import register

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from eshop import settings
from eshop.views import (home_page, header, footer, login_page,
                         register_page, log_out)
from eshop_products.views import products_categories_partial
from eshop_contact.views import contact_us_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name='home'),
    path('header',header, name='header'),
    path('footer',footer, name='footer'),
    path('contact-us',contact_us_page, name='contact'),
    path('login',login_page, name='login'),
    path('register',register_page, name='register'),
    path('logout',log_out, name='logout'),
    path('', include('eshop_products.urls', namespace='products')),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),
    path('',include('eshop_order.urls', namespace='order')),
    path('',include('eshop_profile.urls', namespace='profile')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_order/urls.py
from django.urls import path
from eshop_order.views import add_new_order, cart, send_request, verify, remove_cart_item

app_name = 'eshop_order'
urlpatterns = [
    path('add_new_order',add_new_order),
    path('cart',cart),
    path('request/', send_request, name='request'),
    path('verify/<order_id>', verify, name='verify'),
    path('remove-cart-item/<detail_id>', remove_cart_item, name=' remove_cart_item'),
]

eshop_products/urls.py
from django.urls import path
from eshop_products.views import (ProductsList, product_detail, SearchProducts,
                                  ProductsListByCategory)

app_name = 'eshop_products'
urlpatterns = [
    path('products', ProductsList.as_view(), name='products_list'),
    path('products/<product_id>/<title>', product_detail, name='product_detail'),
    path('products/search',SearchProducts.as_view()),
    path('products/<category_name>',ProductsListByCategory.as_view()),
]

templates/base/base.html
{% load render_partial %}
{% render_partial 'header' %}
{% block contents%}

{% endblock %}
{% render_partial 'footer' %}

templates/base/footer.html
{% load static %}
<!--Footer Start-->
  <footer id="footer">
    <div class="fpart-first">
      <div class="container">
        <div class="row">
          <div class="contact col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <h5>اطلاعات تماس</h5>
            <ul>
              <li class="address"><i class="fa fa-map-marker"></i>{{setting.adress}}</li>
              <li class="mobile"><i class="fa fa-phone"></i>{{setting.phone}}</li>
              <li class="mobile"><i class="fa fa-phone"></i>{{setting.fax}}</li>
              <li class="email"><i class="fa fa-envelope"></i>برقراری ارتباط از طریق <a href="{% url 'contact' %}">تماس با ما</a>
            </ul>
          </div>
          <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
            <h5>حساب من</h5>
            <ul>
              <li><a href="{{ '/profile' }}">حساب کاربری</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="fpart-second">
      <div class="container">
        <div id="powered" class="clearfix">
          <div class="powered_text pull-left flip">
            <p>{{setting.copy_right}}</p>
          </div>
          <div class="social pull-right flip">
            <a href="{{setting.instagram}}" target="_blank"> <img data-toggle="tooltip" src="{{setting.image_thumbnail.url}}" alt="Instagram" title="Instagram"> </a>
          </div>
        </div>
        <div class="bottom-row">
          <div class="custom-text text-center">
            <p>{{setting.about}}</p>
          </div>
        </div>
      </div>
    </div>
    <div id="back-top"><a data-toggle="tooltip" title="بازگشت به بالا" href="javascript:void(0)" class="backtotop"><i class="fa fa-chevron-up"></i></a></div>
  </footer>
  <!--Footer End-->
</div>
<!-- JS Part Start-->
<script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.easing-1.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dcjqaccordion.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<!-- JS Part End-->
</body>
</html>

templates/base/header.html
{% load static%}
{% load render_partial %}
<!DOCTYPE html>
<html dir="rtl">
<head>
<meta charset="UTF-8" />
<meta name="format-detection" content="telephone=no" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href="image/favicon.png" rel="icon" />
<title>فروشگاه کدیتی</title>
<meta name="description" content="Responsive and clean html template design for any kind of ecommerce webshop">
<!-- CSS Part Start-->
<link rel="stylesheet" type="text/css" href="{% static 'js/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'js/bootstrap/css/bootstrap-rtl.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.transitions.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet-rtl.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive-rtl.css' %}" />
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans' type='text/css'>
<!-- CSS Part End-->
</head>
<body>
<div class="wrapper-wide">
  <div id="header">
    <!-- Top Bar Start-->
    <nav id="top" class="htop">
      <div class="container">
        <div class="row"> <span class="drop-icon visible-sm visible-xs"><i class="fa fa-align-justify"></i></span>
          <div class="pull-left flip left-top">
            <div class="links">
              <ul>
                <li class="mobile"><i class="fa fa-phone"></i>{{setting.phone}}</li>
                <li class="email"><a href="mailto:info@marketshop.com"><i class="fa fa-envelope"></i>{{setting.email}}</a></li>
              </ul>
            </div>
          </div>
          <div id="top-links" class="nav pull-right flip">
            <ul>
              {% if request.user.is_authenticated %}
                <li><a href="{% url 'logout' %}">خروج</a></li>
                <li><a href="/profile">حساب کاربری</a></li>
              {% else %}
                <li><a href="{% url 'login' %}">ورود</a></li>
                <li><a href="{% url 'register' %}">ثبت نام</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <!-- Top Bar End-->
    <!-- Header Start-->
    <header class="header-row">
      <div class="container">
        <div class="table-container">
          <!-- Logo Start -->
          <div class="col-sm-3">
            <div id="logo"><a href="/#"><img class="img-responsive" src="{% static 'image/image/codity.png' %}" title="فروشگاه کدیتی" alt="فروشگاه کدیتی" /></a></div>
          </div>
          <!-- Logo End -->
          <!-- جستجو Start-->
          <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12 inner">
            <div id="search" class="input-group">
              <form action="/products/search" method="get">
                <input id="filter_name" type="text" name="q" value="{{ request.GET.q }}" placeholder="جستجو" class="form-control input-lg" />
                <button type="button" class="button-search"><i class="fa fa-search"></i></button>
              </form>
            </div>
          </div>
          <!-- جستجو End-->
        </div>
      </div>
    </header>
    <!-- Header End-->
    <div class="container">
      <nav id="menu" class="navbar">
        <div class="navbar-header"> <span class="visible-xs visible-sm"> منو <b></b></span></div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><a class="home_link" title="خانه" href="{% url 'home' %}"><span>خانه</span></a></li>
            <li><a class="" href="{% url 'products:products_list' %}"><span>فروشگاه</span></a></li>
            <li class="mega-menu dropdown"><a>دسته ها</a>
              <div class="dropdown-menu">
                  <div>
                    <ul>
                       {% render_partial 'products_categories_partial' %}
                    </ul>
                  </div>
              </div>
            </li>
            <li class="dropdown information-link"><a>برگه ها</a>
              <div class="dropdown-menu">
                <ul>
                  <li><a href="{% url 'login' %}">ورود</a></li>
                  <li><a href="{% url 'register' %}">ثبت نام</a></li>
                  <li><a href="{% url 'contact' %}">تماس با ما</a></li>
                </ul>
                <ul>
                  <li><a href="{% url 'products:products_list' %}">محصولات</a></li>
                  <li><a href="{{ '/cart' }}">سبد خرید</a></li>
                  <li><a href="{% url 'eshop_order:request' %}">تسویه حساب</a></li>
                </ul>
              </div>
            </li>
            <li class="contact-link"><a href="{% url 'contact' %}">تماس با ما</a></li>
            <li class="custom-link-right"><a href="{% url 'products:products_list' %}" target="_blank"> همین حالا بخرید!</a></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>