eshop/urls.py
from multiprocessing.resource_tracker import register

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from eshop import settings
from eshop.views import (home_page, header, footer, login_page,
                         register_page, log_out)
from eshop_products.views import products_categories_partial
from eshop_contact.views import contact_us_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name='home'),
    path('header',header, name='header'),
    path('footer',footer, name='footer'),
    path('contact-us',contact_us_page, name='contact'),
    path('login',login_page, name='login'),
    path('register',register_page, name='register'),
    path('logout',log_out, name='logout'),
    path('', include('eshop_products.urls', namespace='products')),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),
    path('',include('eshop_order.urls', namespace='order')),
    path('',include('eshop_profile.urls', namespace='profile')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_profile/urls.py
from django.urls import path
from eshop_profile.views import profile_main_page, profile_user_order, profile_setting

app_name = 'eshop_profile'
urlpatterns = [
    path('profile', profile_main_page),
    path('profile/orders', profile_user_order, name='orders'),
    path('profile/setting', profile_setting, name='setting')
]

eshop_profile/models.py
from django.db import models

# Create your models here.

eshop_profile/forms.py
from django import forms

class UserEditProfileForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':'نام خود را وارد نمایید'}),
        label="نام:"
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':'نام خانوادگی خود را وارد نمایید'}),
        label="نام خانوادگی:"
    )

eshop_profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render
from eshop_profile.forms import UserEditProfileForm


# Create your views here.
@login_required(login_url='/login')
def profile_main_page(request):
    context ={}
    return render(request,'profile_main_page.html',context)

@login_required(login_url='/login')
def profile_user_order(request):
    context = {}
    return render(request,'profile_user_orders.html',context)

@login_required(login_url='/login')
def profile_sidebar(request):
    context = {}
    return render(request, 'profile_sidebar.html', context)

@login_required(login_url='/login')
def profile_setting(request):
    user_id = request.user.id
    user = User.objects.get(id=user_id)
    if user is None:
        raise Http404()

    edit_form = UserEditProfileForm(request.POST or None,
        initial={'first_name':user.first_name , 'last_name':user.last_name})
    if edit_form.is_valid():
        first_name = edit_form.cleaned_data.get('first_name')
        last_name = edit_form.cleaned_data.get('last_name')
        user.first_name = first_name
        user.last_name = last_name
        user.save()

    context = {
        'edit_form':edit_form
    }
    return render(request, 'profile_setting.html', context)

eshop_profile/templates/profile_main_page.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% block contents %}
    <div class="container">
      <div class="row">
        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'eshop_profile.views.profile_sidebar' %}
        </aside>
        <!--Right Part End -->
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
            <h1 class="title">پنل کاربر</h1>
        </div>
        <!--Middle Part End -->
      </div>
    </div>
{% endblock %}

eshop_profile/templates/profile_setting.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% block contents %}
    <div class="container">
      <div class="row">
        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'eshop_profile.views.profile_sidebar' %}
        </aside>
        <!--Right Part End -->
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
            <h1 class="title">تنظیمات</h1>
            <form class="form-horizontal" method="post">
                {% csrf_token %}
            <fieldset>
              <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-name">{{edit_form.first_name.label}}</label>
                <div class="col-md-10 col-sm-9">
                  {{edit_form.first_name}}
                </div>
                  {% for error in edit_form.first_name.errors %}
                    <div class="text-danger">{{ error }}</div>
                  {% endfor %}
                </div>

              <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-name">{{edit_form.last_name.label}}</label>
                <div class="col-md-10 col-sm-9">
                  {{edit_form.last_name}}
                </div>
                  {% for error in edit_form.last_name.errors %}
                    <div class="text-danger">{{ error }}</div>
                  {% endfor %}
              </div>

            </fieldset>
            <div class="buttons">
              <div class="pull-right">
                <input class="btn btn-primary" type="submit" value="ارسال">
              </div>
            </div>
          </form>

        </div>
        <!--Middle Part End -->
      </div>
    </div>
{% endblock %}

eshop_profile/templates/profile_sidebar.html
<ul>
    <li>
        <a href="/profile">پنل کاربر</a>
    </li>
    <li>
        <a href="{% url 'profile:orders' %}">سفارش های من</a>
    </li>
    <li>
        <a href="{% url 'profile:setting' %}">تنظیمات</a>
    </li>
    <li>
        <a href="/logout">خروج</a>
    </li>
</ul>

eshop_profile/templates/profile_user_orders.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% block contents %}
    <div class="container">
      <div class="row">
        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
            {% render_partial 'eshop_profile.views.profile_sidebar' %}
        </aside>
        <!--Right Part End -->
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
            <h1 class="title">سفارش های من</h1>
        </div>
        <!--Middle Part End -->
      </div>
    </div>
{% endblock %}