eshop/urls.py
from multiprocessing.resource_tracker import register

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from eshop import settings
from eshop.views import (home_page, header, footer, login_page,
                         register_page, log_out)
from eshop_products.views import products_categories_partial
from eshop_contact.views import contact_us_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name='home'),
    path('header',header, name='header'),
    path('footer',footer, name='footer'),
    path('contact-us',contact_us_page, name='contact'),
    path('login',login_page, name='login'),
    path('register',register_page, name='register'),
    path('logout',log_out, name='logout'),
    path('', include('eshop_products.urls', namespace='products')),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),
    path('',include('eshop_order.urls', namespace='order')),
    path('',include('eshop_profile.urls', namespace='profile')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_products/urls.py
from django.urls import path
from eshop_products.views import (ProductsList, product_detail, SearchProducts,
                                  ProductsListByCategory)

app_name = 'eshop_products'
urlpatterns = [
    path('products', ProductsList.as_view(), name='products_list'),
    path('products/<product_id>/<title>', product_detail, name='product_detail'),
    path('products/search',SearchProducts.as_view()),
    path('products/<category_name>',ProductsListByCategory.as_view()),
]

eshop_products/models.py
from django.db import models
import os
import random
from django.db.models import Q
from eshop_products_category.models import ProductCategory


def get_file_extension(file):
    base_name = os.path.basename(file)
    name , ext = os.path.splitext(base_name)
    return name , ext

def upload_image(instance, filename):
    rand_name = random.randint(1,9999999999)
    name , ext = get_file_extension(filename)
    final_name = f"{instance.id}-{instance.title}-{rand_name}{ext}"
    return f"products/{final_name}"

class ProductManager(models.Manager):
    def get_active_products(self):
        return self.get_queryset().filter(active=True)

    def get_product_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id, active=True)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def search_products(self, query):
        lookup = (Q(title__icontains=query) | Q(description__icontains=query) |
                  Q(tag__title__icontains=query))
        return self.get_queryset().filter(lookup, active=True).distinct()

    def get_product_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name)

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    price = models.DecimalField(decimal_places=2, max_digits=15, verbose_name ='قیمت')
    image = models.ImageField(upload_to=upload_image,null=True,blank=True,verbose_name='تصویر')
    active = models.BooleanField(default=False, verbose_name='فعال/غیرفعال')
    time = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(ProductCategory, blank=True, verbose_name='دسته بندی')
    featured = models.BooleanField(default=False, verbose_name='محصول ویژه')
    visits = models.IntegerField(default=0, verbose_name='تعداد مشاهده')
    publisher_name = models.CharField(max_length=255, null=True, blank=True, verbose_name="نام ناشر")
    course_duration = models.CharField(max_length=155, null=True, blank=True, verbose_name="مدت زمان دوره")

    objects = ProductManager()

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title
    def get_product_detail_url(self):
        return f"/products/{self.id}/{self.title.replace(' ' , '-')}"

def upload_image_gallery(instance, filename):
    rand_name = random.randint(1,9999999999)
    name , ext = get_file_extension(filename)
    final_name = f"{instance.id}-{instance.title}-{rand_name}{ext}"
    return f"gallery/{final_name}"


class ProductGallery(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')
    image = models.ImageField(upload_to=upload_image_gallery,null=True,blank=True,verbose_name='تصویر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='انتخاب محصول')

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = ' گالری تصاویر'

    def __str__(self):
        return self.title

eshop_products/views.py
from unicodedata import category
from django.http import Http404
from django.shortcuts import render
from django.views.generic.list import ListView
from eshop_products.models import Product, ProductGallery
from eshop_tag.models import Tag
from eshop_products_category.models import ProductCategory
from eshop_order.forms import UserNewOrderForm


# Create your views here.
class ProductsList(ListView):
    template_name = 'products_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Product.objects.get_active_products()

def product_detail(request, *args, **kwargs):
    get_product_id = kwargs['product_id']
    new_order_form = UserNewOrderForm(request.POST or None, initial=({'product_id':get_product_id}))
    title = kwargs['title']

    product = Product.objects.get_product_by_id(get_product_id)
    if product is None:
        raise Http404('محصول مورد نظر یافت نشد!')

    gallery = ProductGallery.objects.filter(product_id=get_product_id)

    related_products = Product.objects.get_queryset().filter(categories__product=product).distinct()
    print(related_products)

    product.visits += 1
    product.save()
    
    featured_products = Product.objects.filter(featured=True)

    context = {
        'product':product,
        'gallery':gallery,
        'related_products':related_products,
        'new_order_form':new_order_form,
        'featured_products':featured_products,   
    }
    
    tag = Tag.objects.first()

    return  render(request, 'product_detail.html', context)

class SearchProducts(ListView):
    template_name = 'products_list.html'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            return Product.objects.search_products(query)
        return Product.objects.get_active_products()

class ProductsListByCategory(ListView):
    template_name = 'products_list.html'
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        print(category_name)
        categories = ProductCategory.objects.filter(name__iexact=category_name)
        if categories is None:
            raise Http404('صفحه مورد نظر یافت نشد!')
        return Product.objects.get_product_by_category(category_name)

def products_categories_partial(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories':categories
    }
    return render(request,'categories_view_partial.html', context)

eshop_products/templates/categories_view_partial.html
<a href="{% url 'products:products_list' %}">
    <h3 class="subtitle">دسته ها</h3>
</a>
<div class="box-category">
<ul>
    {% for category in categories %}
      <li><a href="/products/{{ category.name }}">{{ category.title }}</a></li>
    {% endfor %}
</ul>
</div>

eshop_products/templates/product_detail.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% block contents %}
    <div class="container">
      <!-- Breadcrumb Start-->
      <ul class="breadcrumb">
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="/#" itemprop="url"><span itemprop="title"><i class="fa fa-home"></i></span></a></li>
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="{% url 'products:products_list' %}" itemprop="url"><span itemprop="title">محصولات</span></a></li>
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a href="" itemprop="url"><span itemprop="title">{{product.title}}</span></a></li>

      </ul>
      <!-- Breadcrumb End-->
      <div class="row">
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <div itemscope="" itemtype="http://schema.org/محصولات">
            <h1 class="title" itemprop="name">{{ product.title }}</h1>
            <div class="row product-info">
              <div class="col-sm-6">
                <div class="image"><div style="height:150px;width:350px;" class="zoomWrapper">
                  <img class="img-responsive" itemprop="image" id="zoom_01" src="{{ product.image.url }}" alt="{{product.title}}" style="position: absolute;">
                </div> </div>
                  <div class="image-additional" id="gallery_01">
                     {% for image_gallery in gallery %}
                        <a class="thumbnail active" href="#" data-zoom-image="{{image_gallery.image.url}}" data-image="{{image_gallery.image.url}}">
                          <img src="{{image_gallery.image.url}}" title="{{image_gallery.title}}" alt="{{image_gallery.title}}">
                        </a>
                     {% endfor %}
                  </div>
              </div>
              <div class="col-sm-6">
                <h1 class="title" style="font-size:18px;" itemprop="name">نام ناشر: {{ product.publisher_name }}</h1>
                <h1 class="title" style="font-size:18px;" itemprop="name">مدت زمان دوره: {{ product.course_duration }}</h1>
              </div>
              <div class="col-sm-6">
                <ul class="price-box">
                  <li class="price" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                    <span class="price">تومان {{ product.price}}</span>
                  </li>
                </ul>
                <div id="product">
                  <div class="cart">
                    <form action="/add_new_order" method="post">
                      {%csrf_token%}
                      <div>
                        <div class="qty">
                          {{new_order_form.product_id}}
                          <label class="control-label" for="input-quantity">تعداد</label>
                          {{new_order_form.count}}
                          <a class="qtyBtn plus" href="javascript:void(0);">+</a><br>
                          <a class="qtyBtn mines" href="javascript:void(0);">-</a>
                          <div class="clear"></div>
                        </div>
                        <button type="submit" id="button-cart" class="btn btn-primary btn-lg">افزودن به سبد خرید</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab-description" data-toggle="tab">توضیحات</a></li>
            </ul>
            <div class="tab-content">
              <div itemprop="description" id="tab-description" class="tab-pane active">
                <div>
                    <p>{{product.description}}</p>
                </div>
              </div>
            </div>
            <h3 class="subtitle">محصولات مرتبط</h3>
            <div class="owl-carousel related_pro">
            {% for product in related_products %}
              <div class="product-thumb">
                <div class="image"><a href="{% url 'products:product_detail' product.id product.title %}"><img src="{{ product.image.url}}" alt="{{ product.title}}" title="{{ product.title}}" class="img-responsive" /></a></div>
                  <div class="caption">
                    <h4><a href="{{ product.get_product_detail_url }}">{{ product.title}}</a></h4>
                    <p class="price">
                        <span class="price-new">{{ product.price }} تومان</span>
                    </p>
                  </div>
                  <div class="button-group">
                   <a href="{{product.get_product_detail_url}}">
                     <button class="btn-primary" type="button" onClick=""><span>مشاهده محصول</span></button>
                   </a>
                </div>
              </div>
            {% endfor %}
          </div>
         </div>
        </div>
        <!--Middle Part End -->
        <!--left Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
          <div class="side-item">
          <!-- Featured محصولات Start-->
          <h3 class="subtitle" style="border-bottom: none; margin-bottom:0">محصولات ویژه</h3>
          <div class="product-list">
            {% for product in featured_products %}
              <div class="product-thumb clearfix">
                <div class="image"><a href="{% url 'products:product_detail' product.id product.title %}"><img src="{{product.image.url}}"  alt="{{product.title}}" title="{{product.title}}" class="img-responsive" /></a></div>
                  <div class="caption">
                    <h4><a href="{% url 'products:product_detail' product.id product.title %}">{{product.title}}</a></h4>
                    <p class="price"><span>{{product.price}} تومان</span></p>
                  </div>
                  <div class="button-group">
                    <a href="{{product.get_product_detail_url}}">
                      <button class="btn-primary" type="button"><span>مشاهده محصول</span></button>
                    </a>
                  </div>
              </div>
            {% endfor %}
          </div>
          <!-- Featured محصولات End-->
          </div>
            {% render_partial 'products_categories_partial' %}
        </aside>
        <!--left Part End -->
      </div>
    </div>
{% endblock %}

eshop_products/templates/product_item_component.html
<div class="product-layout product-grid col-lg-5ths col-md-5ths col-sm-4 col-xs-12">
  <div class="product-thumb">
    <div class="image"><a href="{{product.get_product_detail_url}}"><img src="{{ product.image.url }}" alt=" {{ product.title }} " title=" {{ product.title }}" class="img-responsive"></a></div>
    <div>
      <div class="caption">
        <h4><a href="{{product.get_product_detail_url}}"> {{ product.title }} </a></h4>
        <p class="description">{{ product.description}}</p>
        <p class="price"><span class="price">{{product.price}} تومان</span></p>
      </div>
      <div class="button-group">
        <a href="{{product.get_product_detail_url}}">
          <button class="btn-primary" type="button"><span>مشاهده محصول</span></button>
        </a>
      </div>
    </div>
  </div>
</div>

eshop_products/templates/products_list.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% load static %}
{% block contents %}
<div class="container">
      <!-- Breadcrumb Start-->
      <ul class="breadcrumb">
        <li><a href="/#"><i class="fa fa-home"></i></a></li>
        <li><a href="{% url 'products:products_list' %}">محصولات</a></li>
      </ul>
      <!-- Breadcrumb End-->
      <div class="row">
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
          <h1 class="title">لیست محصولات</h1>
          <br>
          <div class="row products-category">
              {% for product in page_obj %}
                {% include 'product_item_component.html' with product=product %}
              {% endfor %}
          </div>
          <div class="row">
            <div class="col-sm-6 text-left">
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                {% endif %}
                {% for page in paginator.page_range  %}
                  {% if page == page_obj.number %}
                        <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                  {% else %}
                        <li><a href="?page={{ page }}">{{ page }}</a></li>
                  {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                  <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <!--Middle Part End -->
        <!--Right Part Start -->
        <aside id="column-right" class="col-sm-3 hidden-xs">
          {% render_partial 'products_categories_partial' %}
        </aside>
        <!--Right Part End -->
      </div>
</div>
{% endblock %}