eshop/urls.py
from multiprocessing.resource_tracker import register

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from eshop import settings
from eshop.views import (home_page, header, footer, login_page,
                         register_page, log_out)
from eshop_products.views import products_categories_partial
from eshop_contact.views import contact_us_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name='home'),
    path('header',header, name='header'),
    path('footer',footer, name='footer'),
    path('contact-us',contact_us_page, name='contact'),
    path('login',login_page, name='login'),
    path('register',register_page, name='register'),
    path('logout',log_out, name='logout'),
    path('', include('eshop_products.urls', namespace='products')),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),
    path('',include('eshop_order.urls', namespace='order')),
    path('',include('eshop_profile.urls', namespace='profile')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_order/urls.py
from django.urls import path
from eshop_order.views import add_new_order, cart, send_request, verify, remove_cart_item

app_name = 'eshop_order'
urlpatterns = [
    path('add_new_order',add_new_order),
    path('cart',cart),
    path('request/', send_request, name='request'),
    path('verify/<order_id>', verify, name='verify'),
    path('remove-cart-item/<detail_id>', remove_cart_item, name=' remove_cart_item'),
]

eshop_products/urls.py
from django.urls import path
from eshop_products.views import (ProductsList, product_detail, SearchProducts,
                                  ProductsListByCategory)

app_name = 'eshop_products'
urlpatterns = [
    path('products', ProductsList.as_view(), name='products_list'),
    path('products/<product_id>/<title>', product_detail, name='product_detail'),
    path('products/search',SearchProducts.as_view()),
    path('products/<category_name>',ProductsListByCategory.as_view()),
]

eshop_order/models.py
from django.db import models
from django.contrib.auth.models import User
from eshop_products.models import Product


# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    paid = models.BooleanField(default=False, verbose_name='پرداخت شده/نشده')
    pay_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبدهای خرید'

    def __str__(self):
        return self.user.get_full_name()

    def total_price(self):
        amount = 0
        for detail in self.orderdetail_set.all():
            amount += detail.price * detail.count
        return amount

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField()
    price = models.IntegerField()

    class Meta:
        verbose_name = 'جز‌ئیات سبد خرید'
        verbose_name_plural = 'جزئیات سبدهای خرید'

    def __str__(self):
        return self.product.title

    def product_sum_in_cart(self):
        return self.price * self.count

eshop_order/forms.py
from django import forms


class UserNewOrderForm(forms.Form):
    product_id = forms.IntegerField(
        widget=forms.HiddenInput()
    )
    count = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class':'form-control','id':'input-quantity'}),
        initial=1
    )

eshop_order/views.py
from django.shortcuts import render, redirect
from eshop_order.forms import UserNewOrderForm
from eshop_order.models import Order, OrderDetail
from eshop_products.models import Product
from django.contrib.auth.decorators import login_required
# zarinpal import file
from django.http import HttpResponse, Http404
from django.shortcuts import redirect
import requests
import json
import time

# Create your views here.
@login_required(login_url='/login')
def add_new_order(request):
    new_order_form = UserNewOrderForm(request.POST or None)
    if new_order_form.is_valid():
        order = Order.objects.filter(user_id=request.user.id, paid=False).first()
        if order is None:
            order = Order.objects.create(user_id=request.user.id, paid=False)

        product_id = new_order_form.cleaned_data.get('product_id')
        product = Product.objects.get_product_by_id(product_id)
        count= new_order_form.cleaned_data.get('count')
        if count < 0:
            count = 1
        order.orderdetail_set.create(product_id=product.id, count=count, price=product.price)
        return redirect(f"/products/{product.id}/{product.title.replace(' ', '-')}")

@login_required(login_url='/login')
def cart(request):
    context = {
        'order': None,
        'details': None,
        'total_price': 0,
    }
    open_order: Order = Order.objects.filter(user_id=request.user.id , paid=False).first()
    if open_order is not None:
        context['order'] = open_order,
        context['details'] = open_order.orderdetail_set.all()
        context['total_price'] = open_order.total_price()

    return render(request, 'cart_page.html', context)

@login_required(login_url='/login')
def remove_cart_item(request, *args, **kwargs):
    detail_id = kwargs['detail_id']
    order_detail = OrderDetail.objects.get_queryset().get(id=detail_id)
    if order_detail is not None:
        order_detail.delete()
        return redirect('/cart')
    raise Http404()


MERCHANT = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
amount = 11000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
email = 'email@example.com'  # Optional
mobile = '09123456789'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'http://localhost:8001/verify'

def send_request(request):
    open_order: Order = Order.objects.filter(user_id=request.user.id , paid=False).first()
    if open_order is not None:
        total_price = open_order.total_price()
        req_data = {
            "merchant_id": MERCHANT,
            "amount": total_price,
            "callback_url": f"{CallbackURL}/{open_order.id}",
            "description": description,
            "metadata": {"mobile": mobile, "email": email}
        }
        req_header = {"accept": "application/json",
                      "content-type": "application/json'"}
        req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
            req_data), headers=req_header)
        authority = req.json()['data']['authority']
        if len(req.json()['errors']) == 0:
            return redirect(ZP_API_STARTPAY.format(authority=authority))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")

def verify(request, *args, **kwargs):
    order_id = kwargs['order_id']
    t_status = request.GET.get('Status')
    t_authority = request.GET['Authority']
    if request.GET.get('Status') == 'OK':
        req_header = {"accept": "application/json",
                      "content-type": "application/json'"}
        req_data = {
            "merchant_id": MERCHANT,
            "amount": amount,
            "authority": t_authority
        }
        req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
        if len(req.json()['errors']) == 0:
            t_status = req.json()['data']['code']
            if t_status == 100:
                order = Order.objects.get_queryset().get(id=order_id)
                order.paid = True
                order.pay_date = time.time()
                order.save()
                return HttpResponse('Transaction success.\nRefID: ' + str(
                    req.json()['data']['ref_id']
                ))
            elif t_status == 101:
                return HttpResponse('Transaction submitted : ' + str(
                    req.json()['data']['message']
                ))
            else:
                return HttpResponse('Transaction failed.\nStatus: ' + str(
                    req.json()['data']['message']
                ))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
    else:
        return HttpResponse('Transaction failed or canceled by user')

eshop_order/templates/cart_page.html
{% extends 'base/base.html' %}
{% block contents %}
    <div id="container">
    <div class="container">
      <!-- Breadcrumb Start-->
      <ul class="breadcrumb">
        <li><a href="/#"><i class="fa fa-home"></i></a></li>
        <li><a href="{{ '/cart' }}">سبد خرید</a></li>
      </ul>
      <!-- Breadcrumb End-->
      <div class="row">
        <!--Middle Part Start-->
        <div id="content" class="col-sm-12">
          <h1 class="title">سبد خرید</h1>
            <div class="table-responsive">
                {% if order != None and details|length > 0 %}
                  <table class="table table-bordered">
                <thead>
                  <tr>
                    <td class="text-center">تصویر</td>
                    <td class="text-left">نام محصول</td>
                    <td class="text-left">کد محصول</td>
                    <td class="text-left">تعداد</td>
                    <td class="text-right">قیمت واحد</td>
                    <td class="text-right">کل</td>
                    <td class="text-right">عملیات</td>
                  </tr>
                </thead>
                <tbody>
                    {% for detail in details %}
                     <tr>
                        <td class="text-center">
                            <a href="{% url 'eshop_products:product_detail' detail.product.id detail.product.title %}">
                                <img src="{{detail.product.image.url}}" alt="{{detail.product.title}}" style="width:100px; height:100px" class="img-thumbnail">
                            </a></td>
                        <td class="text-left"><a href="{% url 'eshop_products:product_detail' detail.product.id detail.product.title %}">{{detail.product.title}}</a><br>
                        <td class="text-left">{{detail.product.id}}</td>
                        <td class="text-left"><div class="input-group btn-block quantity">
                            <span>{{detail.count}}</span>
                            <span class="input-group-btn">
                            </span></div></td>
                        <td class="text-right"> {{detail.price}} تومان</td>
                        <td class="text-right">{{detail.product_sum_in_cart}} تومان</td>
                         <td>
                             <div class="pull-right">
                                 <a href="/remove-cart-item/{{detail.id}}" class="btn btn-danger">حذف از سبد خرید</a>
                             </div>
                         </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
                {% else %}
                    <p>هیچ محصولی در سبد خرید یافت نشد!</p>
                {% endif %}
            </div>
          <h2 class="subtitle">حالا مایلید چه کاری انجام دهید؟</h2>
          <div class="row">
            <div class="col-sm-4 col-sm-offset-8">
              <table class="table table-bordered">
                <tbody>
                <tr>
                  <td class="text-right"><strong>جمع کل:</strong></td>
                  <td class="text-right">{{total_price}} تومان</td>
                </tr>
              </tbody></table>
            </div>
          </div>
          <div class="buttons">
            <div class="pull-left"><a href="{% url 'products:products_list' %}" class="btn btn-default">ادامه خرید</a></div>
            <div class="pull-right"><a href="/request" class="btn btn-primary">تسویه حساب</a></div>
          </div>
        </div>
        <!--Middle Part End -->
      </div>
    </div>
    </div>
{% endblock %}